# HR Analytics & Employee Attrition Analysis

## 01 - Data Cleaning

This notebook prepares the HR employee dataset for analysis.

### Objectives
- Load the cleaned HR dataset
- Inspect the dataset structure
- Check data types
- Check missing values
- Check duplicate records
- Validate categorical values
- Validate numerical columns
- Validate analytical grouping columns
- Calculate baseline attrition metrics
- Save the final Python-ready dataset

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("../data/cleaned/HR_Cleaned_Data.csv")

In [3]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,...,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Income_Group,Tenure_Group,Age_Group
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,2,...,8,0,1,6,4,0,5,Medium,6-10 Years,35-44
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,2,3,...,10,3,3,10,7,1,7,Medium,6-10 Years,45-54
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,4,...,7,3,3,0,0,0,0,Low,0-1 Years,35-44
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,5,4,...,8,3,3,8,7,3,0,Low,6-10 Years,25-34
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,7,1,...,6,3,3,2,2,2,2,Medium,2-5 Years,25-34

In [5]:
expected_rows = 1470

print("Actual rows:", len(df))
print("Expected rows:", expected_rows)

if len(df) == expected_rows:
    print("Row count validation: PASS")
else:
    print("Row count validation: CHECK REQUIRED")

Actual rows: 1470
Expected rows: 1470
Row count validation: PASS

In [5]:
df.columns.tolist()

['Age',
 'Attrition',
 'BusinessTravel',
 'DailyRate',
 'Department',
 'DistanceFromHome',
 'Education',
 'EducationField',
 'EmployeeNumber',
 'EnvironmentSatisfaction',
 'Gender',
 'HourlyRate',
 'JobInvolvement',
 'JobLevel',
 'JobRole',
 'JobSatisfaction',
 'MaritalStatus',
 'MonthlyIncome',
 'MonthlyRate',
 'NumCompaniesWorked',
 'OverTime',
 'PercentSalaryHike',
 'PerformanceRating',
 'RelationshipSatisfaction',
 'StockOptionLevel',
 'TotalWorkingYears',
 'TrainingTimesLastYear',
 'WorkLifeBalance',
 'YearsAtCompany',
 'YearsInCurrentRole',
 'YearsSinceLastPromotion',
 'YearsWithCurrManager',
 'Income_Group',
 'Tenure_Group',
 'Age_Group']

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   str
 2   BusinessTravel            1470 non-null   str
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   str
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   str
 8   EmployeeNumber            1470 non-null   int64
 9   EnvironmentSatisfaction   1470 non-null   int64
 10  Gender                    1470 non-null   str
 11  HourlyRate                1470 non-null   int64
 12  JobInvolvement            1470 non-null   int64
 13  JobLevel                  1470 non-null   int64
 14  JobRole                   1470 non-null   str
 15  JobSatisfaction           1470 non-null   int64
 16  MaritalStatus             1470 non-null   str
 17  MonthlyIncome             1470 non-null   int64
 18  MonthlyRate               1470 non-null   int64
 19  NumCompaniesWorked        1470 non-null   int64
 20  OverTime                  1470 non-null   str
 21  PercentSalaryHike         1470 non-null   int64
 22  PerformanceRating         1470 non-null   int64
 23  RelationshipSatisfaction  1470 non-null   int64
 24  StockOptionLevel          1470 non-null   int64
 25  TotalWorkingYears         1470 non-null   int64
 26  TrainingTimesLastYear     1470 non-null   int64
 27  WorkLifeBalance           1470 non-null   int64
 28  YearsAtCompany            1470 non-null   int64
 29  YearsInCurrentRole        1470 non-null   int64
 30  YearsSinceLastPromotion   1470 non-null   int64
 31  YearsWithCurrManager      1470 non-null   int64
 32  Income_Group              1470 non-null   str
 33  Tenure_Group              1470 non-null   str
 34  Age_Group                 1470 non-null   str
dtypes: int64(24), str(11)
memory usage: 402.1 KB

In [7]:
missing_values = df.isnull().sum()

missing_values[missing_values > 0]

Series([], dtype: int64)

In [8]:
df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
Income_Group                0
Tenure_Group                0
Age_Group                   0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [6]:
print("Total rows:", len(df))
print("Unique EmployeeNumber:", df["EmployeeNumber"].nunique())

if len(df) == df["EmployeeNumber"].nunique():
    print("EmployeeNumber uniqueness: PASS")
else:
    print("EmployeeNumber uniqueness: CHECK REQUIRED")

Total rows: 1470
Unique EmployeeNumber: 1470
EmployeeNumber uniqueness: PASS

In [11]:
df["Attrition"].value_counts()

Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [12]:
df["Department"].value_counts()

Department
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64

In [14]:
df["BusinessTravel"].value_counts()

BusinessTravel
Travel_Rarely        1043
Travel_Frequently     277
Non-Travel            150
Name: count, dtype: int64

In [15]:
df.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1024.865306,2.721769,65.891156,2.729932,2.063946,2.728571,...,3.153741,2.712245,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,602.024335,1.093082,20.329428,0.711561,1.106940,1.102846,...,0.360824,1.081209,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.000000,1.000000,30.000000,1.000000,1.000000,1.000000,...,3.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,491.250000,2.000000,48.000000,2.000000,1.000000,2.000000,...,3.000000,2.000000,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1020.500000,3.000000,66.000000,3.000000,2.000000,3.000000,...,3.000000,3.000000,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1555.750000,4.000000,83.750000,3.000000,3.000000,4.000000,...,3.000000,4.000000,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,2068.000000,4.000000,100.000000,4.000000,5.000000,4.000000,...,4.000000,4.000000,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [16]:
df[df["Age"] <= 0]

Empty DataFrame
Columns: [Age, Attrition, BusinessTravel, DailyRate, Department, DistanceFromHome, Education, EducationField, EmployeeNumber, EnvironmentSatisfaction, Gender, HourlyRate, JobInvolvement, JobLevel, JobRole, JobSatisfaction, MaritalStatus, MonthlyIncome, MonthlyRate, NumCompaniesWorked, OverTime, PercentSalaryHike, PerformanceRating, RelationshipSatisfaction, StockOptionLevel, TotalWorkingYears, TrainingTimesLastYear, WorkLifeBalance, YearsAtCompany, YearsInCurrentRole, YearsSinceLastPromotion, YearsWithCurrManager, Income_Group, Tenure_Group, Age_Group]
Index: []

[0 rows x 35 columns]

In [17]:
df[df["YearsAtCompany"] < 0]

Empty DataFrame
Columns: [Age, Attrition, BusinessTravel, DailyRate, Department, DistanceFromHome, Education, EducationField, EmployeeNumber, EnvironmentSatisfaction, Gender, HourlyRate, JobInvolvement, JobLevel, JobRole, JobSatisfaction, MaritalStatus, MonthlyIncome, MonthlyRate, NumCompaniesWorked, OverTime, PercentSalaryHike, PerformanceRating, RelationshipSatisfaction, StockOptionLevel, TotalWorkingYears, TrainingTimesLastYear, WorkLifeBalance, YearsAtCompany, YearsInCurrentRole, YearsSinceLastPromotion, YearsWithCurrManager, Income_Group, Tenure_Group, Age_Group]
Index: []

[0 rows x 35 columns]

In [18]:
df[df["DistanceFromHome"] <= 0]

Empty DataFrame
Columns: [Age, Attrition, BusinessTravel, DailyRate, Department, DistanceFromHome, Education, EducationField, EmployeeNumber, EnvironmentSatisfaction, Gender, HourlyRate, JobInvolvement, JobLevel, JobRole, JobSatisfaction, MaritalStatus, MonthlyIncome, MonthlyRate, NumCompaniesWorked, OverTime, PercentSalaryHike, PerformanceRating, RelationshipSatisfaction, StockOptionLevel, TotalWorkingYears, TrainingTimesLastYear, WorkLifeBalance, YearsAtCompany, YearsInCurrentRole, YearsSinceLastPromotion, YearsWithCurrManager, Income_Group, Tenure_Group, Age_Group]
Index: []

[0 rows x 35 columns]

In [19]:
df["Age_Group"].value_counts()

Age_Group
25-34       554
35-44       505
45-54       245
Under 25     97
55+          69
Name: count, dtype: int64

In [20]:
df["Tenure_Group"].value_counts()

Tenure_Group
2-5 Years     561
6-10 Years    448
10+ Years     246
0-1 Years     215
Name: count, dtype: int64

In [21]:
df["Income_Group"].value_counts()

Income_Group
Medium    640
High      435
Low       395
Name: count, dtype: int64

In [22]:
attrition_counts = df["Attrition"].value_counts()

attrition_counts

Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [8]:
attrition_rate = (
    df["Attrition"].eq("Yes").mean() * 100
)

print(f"Overall Attrition Rate: {attrition_rate:.2f}%")

Overall Attrition Rate: 16.12%

In [9]:
print("Dataset Shape:", df.shape)
print("Duplicate Rows:", df.duplicated().sum())
print("Missing Values:", df.isnull().sum().sum())
print("Unique Employees:", df["EmployeeNumber"].nunique())
print("Employees Who Left:", (df["Attrition"] == "Yes").sum())
print("Employees Who Stayed:", (df["Attrition"] == "No").sum())
print(f"Attrition Rate: {attrition_rate:.2f}%")
print("Departments:", df["Department"].nunique())
print("Job Roles:", df["JobRole"].nunique())

Dataset Shape: (1470, 35)
Duplicate Rows: 0
Missing Values: 0
Unique Employees: 1470
Employees Who Left: 237
Employees Who Stayed: 1233
Attrition Rate: 16.12%
Departments: 3
Job Roles: 9

In [25]:
df.to_csv(
    "../data/cleaned/HR_Python_Cleaned_Data.csv",
    index=False
)

In [26]:
print("Python-cleaned dataset saved successfully.")

Python-cleaned dataset saved successfully.